// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payslip.Data;

#nullable disable

namespace Payslip.Migrations
{
    [DbContext(typeof(SalarySlipContext))]
    [Migration("20240809141311_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payslip.Models.SalarySlip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ArrearsIfAny")
                        .HasColumnType("numeric");

                    b.Property<string>("Bank")
                        .HasColumnType("text");

                    b.Property<long>("BankAccountNo")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BasicDA")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<int>("EMPID")
                        .HasColumnType("integer");

                    b.Property<decimal>("ESIDeductions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExecutiveAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossDeductions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HRA")
                        .HasColumnType("numeric");

                    b.Property<int>("LOPDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("LoanDeduction")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherEarnings")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OverTimeEarnings")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OverTimeEarningsAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PFEmployeeContribution")
                        .HasColumnType("numeric");

                    b.Property<int>("PaidDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProfessionTax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalaryAdvance")
                        .HasColumnType("numeric");

                    b.Property<string>("SalaryCreditMode")
                        .HasColumnType("text");

                    b.Property<decimal>("TDS")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalCalendarDays")
                        .HasColumnType("integer");

                    b.Property<long>("UAN")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SalarySlips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
